version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: tunx4
      POSTGRES_PASSWORD: xuantu123
      POSTGRES_DB: postgres
      POSTGRES_HOST: tunx4-p3-db.c4yr6hji7zxd.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: tunx4-p3-dev
      JWT_SECRET: hello
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: tunx4
      POSTGRES_PASSWORD: xuantu123
      POSTGRES_DB: postgres
      POSTGRES_HOST: tunx4-p3-db.c4yr6hji7zxd.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: tunx4-p3-dev
      JWT_SECRET: hello
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
